### ISSUE TITLE
inconsistencies

### ISSUE THREAD

**Issue by BluCobalt** [Legacy-Fabric/multimc-instance-creator#1]
versions 1.8.9>= don't show the /Fabric in the menu but still actually work for loading mods
versions 1.7> don't work, but as far as i can tell is a loader issue

**Comment by thecatcore** [comment]
for 1.7> you need to add the "noapplet" traits somewhere.
Example here: https://github.com/Grayray75/LegacyFabric-MultiMC/blob/main/src/legacy_fabric_1.4.7/patches/net.fabricmc.intermediary.json#L10

**Comment by BluCobalt** [comment]
Alright i can figure that out tomorrow

**Comment by BluCobalt** [comment]
> for 1.7> you need to add the "noapplet" traits somewhere. Example here: https://github.com/Grayray75/LegacyFabric-MultiMC/blob/main/src/legacy_fabric_1.4.7/patches/net.fabricmc.intermediary.json#L10

fixed this issue; instances for those should work now.

what about the fabric branding ingame? should we make an issue upstream?

**Comment by thecatcore** [comment]
Hm, upstream already refused to fix branding for those versions so it is implemented in API rn

**Comment by BluCobalt** [comment]
Fixed with latest commits
